### ISSUE TITLE
Question 43 image reference incorrect

### ISSUE THREAD

**Issue by b3n3w** [Ditectrev/Microsoft-Azure-AZ-104-Microsoft-Azure-Administrator-Practice-Tests-Exams-Questions-Answers#1]
[![Question 43 part 1](images/question43.jpg)](https://github.com/Ditectrev/Microsoft-Azure-AZ-104-Microsoft-Azure-Administrator-Practice-Tests-Exams-Questions-Answers/blob/c569d81311a073bdf5ce8a2ccc08d0f4fa37a51d/README.md?plain=1#L529)

question43.jpg does not exist. In image folder the filename is question43_1.jpg

**Comment by danieldanielecki** [comment]
Merged, but this course is still WIP (Work in Progress), and hence these images aren't really organized yet. I advice to make some kind of error handling mechanism in the iOS app, because when the app is broken if just 1 asset will download than could've been a nice improvement :-)
